server:
  port: 8081

security:
  jwt:
    key-store: classpath:authservice.jks
    key-store-password: ${KEYSTORE_PASSWORD}
    key-pair-alias: ${KEYSTORE_ALIAS}
    key-pair-password: ${KEYSTORE_PASSWORD}

spring:
  application:
    name: authservice

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    platform: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
